# Generated by Django 5.1.1 on 2024-11-05 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suvery_name', models.CharField(max_length=200)),
                ('Survey_description', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=20)),
                ('Time_created', models.DateTimeField()),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_description', models.CharField(max_length=200)),
                ('Question_type', models.CharField(max_length=10)),
                ('Survey_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools537Project.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=200)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools537Project.questions')),
                ('Survey_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools537Project.survey')),
            ],
        ),
    ]
