# Generated by Django 5.1.1 on 2024-11-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools537Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='Suvery_name',
            new_name='Survey_name',
        ),
        migrations.AlterField(
            model_name='survey',
            name='Time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
